---
name: Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  run-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v7
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
